#:schema node_modules/wrangler/config-schema.json
name = "data-api"
main = "src/index.ts"
compatibility_date = "2024-10-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "node_modules/.bin/esbuild src/index.ts --bundle --format=esm --target=es2020 --outfile=dist/index.js --minify"

#[build.upload]
#format = "modules"
#main = "dist/index.js"

[esbuild]
bundle = true
minify = true
format = "esm"
target = "es2020"
sourcemap = true

[observability]
enabled = true